order: 1
domain_xlen: 1.
domain_ylen: 1.
domain_zlen: 1.
chlen: .25
x_scale: 1
y_scale: 1
z_scale: 1 
weak_scale: 1
h_scale: 1
boundary_report: 0
nspecies: 0
init_only: 0
grid_only: 0
discr_only: 0
inviscid_only: 0
inert_only: 1
single_gas_only: 0
dummy_rhs_only: 0
adiabatic_boundary: 0
periodic_boundary: 1
do_checkpoint: 0
nviz: 1000
nrestart: 10000
nstatus: 10000
sponge_on: 1
artificial_viscosity_on: 1
timestepping_on: 1
log_dependent: 0
current_dt: 1e-8
t_final: 2e-7
constant_cfl: 0
cfl: .1
integrator: euler
init_pressure: 101325
init_temperature: 1500
init_density: 1.0
health_pres_min: 1
health_pres_max: 1000000
