#!/bin/bash

SUMMARY_FILE_NAME=${1}
YAML_RUN_FILE=${2}
ORDER=${3}
SCALE=${4}
rm -f ${YAML_RUN_FILE}
TIMING_DATE=$(date "+%Y-%m-%d %H:%M")
TIME_SINCE_EPOCH=$(date +%s)

# --- Pull the timings out of the sqlite files generated by logging
STARTUP_TIME=$(runalyzer -m ${SUMMARY_FILE_NAME} -c 'print(q("select $t_init.max").fetchall()[0][0])' | grep -v INFO)
FIRST_STEP=$(runalyzer -m ${SUMMARY_FILE_NAME} -c 'print(sum(p[0] for p in q("select $t_step.max").fetchall()[0:1]))' | grep -v INFO)
MIDDLE_8_STEPS=$(runalyzer -m ${SUMMARY_FILE_NAME} -c 'print(sum(p[0] for p in q("select $t_step.max").fetchall()[2:10]))' | grep -v INFO)

# --- Create a YAML-compatible text snippet with the timing info
printf "run_date: ${TIMING_DATE}\nrun_host: ${TIMING_HOST}\n" > ${YAML_RUN_FILE}
printf "run_epoch: ${TIME_SINCE_EPOCH}\nrun_platform: ${TIMING_PLATFORM}\n" >> ${YAML_RUN_FILE}
printf "order: ${ORDER}\nscale: ${SCALE}\n" >> ${YAML_RUN_FILE}
printf "time_startup: ${STARTUP_TIME}\ntime_first_step: ${FIRST_STEP}\n" >> ${YAML_RUN_FILE}
printf "time_middle_8: ${MIDDLE_8_STEPS}\n---\n" >> ${YAML_RUN_FILE}
